Unfold elements when generating comparison lists
standardhealth/fhir-matches pull request #12
Opened 2022-11-02 12:55 UTC by mint-thompson

Completes task [CIMPL-1024](https://standardhealthrecord.atlassian.net/browse/CIMPL-1024).

When looking through the lists of elements on the StructureDefinitions being compared, try to unfold elements to make comparison pairs. The unfolding code is more or less copied out of SUSHI. Not all intricacies of unfolding are handled: choice elements in particular are not necessarily handled perfectly well, since the existence of choice slices can complicate the set of elements that appear. But, cases other than that should be handled reasonably well by these changes.

2022-11-03 16:21 UTC, cmoesel requested changes
Thanks for this, @mint-thompson! I've left a few individual comments and suggestions.

I also noted that when I run the CLI against a real config (w/ some elements that need unfolding), it dies a pretty quick death.  This is because the rest of the code assumes that the elements in the pairings already exist in the SD.  I don't think we can merge to main in this condition, so we have a few choices:

1. Update the rest of the code to handle missing elements gracefully so it doesn't crash.
2. Update the rest of the code to unfold elements as necessary.
3. Update the `unfold` function to splice the unfolded elements into the SD so that they're already there when the SD gets to the downstream code that needs them.
4. Update the `compareElements` function so that if no `fisher` is passed in, it won't try to dig up elements that are missing. Then update SDReviewer to _not_ pass in the `fisher` (as a temporary measure).

I think I'm comfortable with any of those options for now.

2022-11-09 17:46 UTC, mint-thompson commented on src/utils/Comparison.ts
> +      const profileJson = fisher.fishForFHIR(sd.id, Type.Profile);
You're absolutely correct, I wasn't careful enough when bringing over the unfold function from SUSHI.

2022-11-09 18:08 UTC, mint-thompson commented on src/utils/Comparison.ts
> +    el.contentReference;
That bit of logic is from SUSHI, where it expects to not get anything back from `unfold` when it's a choice element with more than one profile. But, I didn't bring over the second half of that logic, where a choice element with more than one profile gets sent over to `unfoldChoiceElementTypes`. So, I think the answer here is to add something like that in, so that a choice element will get unfolded as long as its available types and profiles have at least one common ancestor.

2022-11-09 18:33 UTC, mint-thompson commented
I think updating `digForElement` to splice in the unfolded elements is correct: we have them now, and they will be needed later. As for dealing with multiple profiles, I think I agree that most of that logic is going to happen elsewhere. I think that the best thing for `unfold` to do is to unfold the base type, since that may end up being sufficient. If necessary, the function that does the comparison later might have to re-unfold using specific profiles.

2022-11-09 23:34 UTC, cmoesel commented on src/utils/Comparison.ts
> +          sdElement.id.startsWith(`${contentRefId}.`)
Ah, yeah.  I think you're probably right.

2022-12-06 18:59 UTC, cmoesel requested changes
It's looking very good.  I have a suggestion to consider as well as some other comments (some of which require no changes in this PR). I've also noted that there is still a difference in npm-shrinkwrap.

I tested this w/ US Core and IPS and it worked exactly as expected! Yay!

2022-12-06 18:59 UTC, cmoesel commented on src/utils/SDUtils.ts
> +  return [];
This is an interesting approach, which I assume came from SUSHI... but it's not what I expected to see (even though I'm probably the one who originally wrote it in SUSHI)!

I think I expected it to expand out all the possible type-slices... So that if one side has only `Observation.value[x]`, but the other side has `Observation.value[x]:valueQuantity`, we'd still be able to get a match.  But maybe the logic to imply a type slice belongs somewhere else (because it's not really unfolding so much as it is making an implied type slice explicit).  What do you think? Should we file a task to make type slices explicit to support an element match when one side is a type slice and the other is a choice containing the type?

2022-12-06 18:59 UTC, cmoesel commented on src/utils/SDUtils.ts
> +function addElementToSD(sd: StructureDefinition, element: ElementDefinition) {
As noted in one of my comments above, we might be able to update the logic so we don't need this function anymore.  Which might be nice because, dang, it's kind of weird, isn't it?

2022-12-06 18:59 UTC, cmoesel commented on test/utils/Comparison.test.ts
> +      defs.add(codeableConceptA);
If this is a common pattern, we might want to consider adding an optional argument to `getFSHtureSD` that takes in the `defs` and adds the SD to them.

2022-12-06 18:59 UTC, cmoesel commented on npm-shrinkwrap.json
> +}
Still getting this:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/2278253/205994924-10350f11-4369-4ca9-b3a7-81dd8cc06adc.png">

2022-12-09 22:35 UTC, cmoesel commented on npm-shrinkwrap.json
> +}
Seems to be fixed in [b3f4f3d](https://github.com/standardhealth/fhir-matches/pull/12/commits/b3f4f3d1bdf2590d71de9d5ab2846ac5c86ceecd).

2022-12-09 22:37 UTC, cmoesel commented on src/utils/SDUtils.ts
> +        elementsToAdd.push(...unfoldedElements);
Ah right. We don't want to leave all the expansions in place if we don't actually find the element. Good call. I guess the other way would be to start by doing a shallow copy of the whole array, operating on the shallow copy, and then assigning it back to the snapshot only if you find what you're looking for.  But I just saw how you implemented it and that works too!

2022-12-09 22:38 UTC, cmoesel commented on src/utils/SDUtils.ts
> +  return [];
I still think we should do this, but I'm find with making it a separate task.

2022-12-09 22:50 UTC, cmoesel approved these changes
This looks good to me -- and I could actually use some of the new support for fishing local defs in my TypeReviewer tests -- so let's get this merged!

2022-12-12 17:09 UTC, merged