Cardinality reviewer
standardhealth/fhir-matches pull request #2
Opened 2022-01-27 16:33 UTC by cmoesel

This implements the cardinality reviewer, which compares profiles element-by-element to look for relationships between element cardinalities.  See the writeup of expected behavior here: https://github.com/standardhealth/fhir-matches/wiki/Reviewers#cardinality

Note that we currently don't detect cases where a sub-element has been profiled in one resource but not in the other (e.g., `Patient.name.given 1..*` in A but not B), because the other will not have that element at all.  Once we have a package-loader and fisher, we can "unfold" elements to get the original sub-elements and then compare. But we don't have that yet.

We also don't do anything with slices or extensions that exist in one profile but not the other.  I think we may want separate reviewers to look at something like that -- so (at least for now) it is out of scope.

_Since this is the first element-level reviewer, please also think about the way it is structured and if it makes sense -- or if there is room for improvement.  Also, let me know what you think of the CLI since I made changes there._

**To Test:** There are some unit tests, but you can also test out the CLI (and you should, since I made changes there).  Here are a few examples that just use profiles from FHIR R4 Core (so they should be in your FHIR cache). Run them and confirm that the results are correct and make sense:
```
ts-node src/app.ts  -a ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-bp.json -b ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-bp.json
```
```
ts-node src/app.ts  -a ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-bp.json -b ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-vitalsigns.json
```
```
ts-node src/app.ts  -a ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-vitalsigns.json -b ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-bp.json
```
```
ts-node src/app.ts  -a ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-bp.json -b ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-vitalspanel.json
```
```
ts-node src/app.ts  -a ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-bp.json -b ~/.fhir/packages/hl7.fhir.r4.core\#4.0.1/package/StructureDefinition-bmi.json
```

2022-01-27 17:05 UTC, cmoesel commented
Also, don't get too excited, but... I added a box!

2022-02-01 14:26 UTC, mint-thompson requested changes
Everything seemed in order when run from the command line. I think your approach for an element-level reviewer is good. I have only minor change requests for this.

2022-02-01 14:26 UTC, mint-thompson commented on src/reviewers/sd/CardinalityReviewer.ts
> +      }
There does not appear to be any test that covers the case of an element being present in `a`, but not present in `b`. Could you add a test that covers this?

2022-02-01 22:38 UTC, cmoesel commented on test/reviewers/sd/CardinalityReviewer.test.ts
> +    it('should assess as equivalent to B cardinality 0..*', () => {
Well, darn it.  I'm still waiting for a more intelligent copy/paste.  I think all of our AI research should go into solving this problem.

2022-02-01 22:39 UTC, cmoesel commented on src/reviewers/sd/CardinalityReviewer.ts
> +      }
Sure thing.  Good idea.

2022-02-01 22:58 UTC, cmoesel commented on test/reviewers/sd/CardinalityReviewer.test.ts
> +    it('should assess as equivalent to B cardinality 0..*', () => {
Addressed in 8acb93a.

2022-02-01 22:58 UTC, cmoesel commented on src/reviewers/sd/CardinalityReviewer.ts
> +      }
Addressed in 8acb93a.

2022-02-02 14:48 UTC, mint-thompson commented on test/reviewers/sd/CardinalityReviewer.test.ts
> +    it('should assess as v B cardinality 1..1', () => {
One of the pastes didn't go through correctly:
```suggestion
    it('should assess as disjoint with B cardinality 1..1', () => {
```

2022-02-02 15:37 UTC, cmoesel commented on test/reviewers/sd/CardinalityReviewer.test.ts
> +    it('should assess as v B cardinality 1..1', () => {
Oh man.  This is embarrassing.  Once again, I need an AI-enabled VS Code plugin to do this all for me.

What's worse is that I _thought_ I double-checked this all yesterday before pushing.  I guess I should have triple-checked.

2022-02-02 15:39 UTC, cmoesel commented on test/reviewers/sd/CardinalityReviewer.test.ts
> +    it('should assess as v B cardinality 1..1', () => {
All the magic is in 4c465c6.  Although I just noticed I could have easily just committed your suggestion.

I must be off my game today.

2022-02-04 14:53 UTC, mint-thompson approved these changes
hooray for element-level reviews!

2022-02-08 22:23 UTC, julianxcarter approved these changes
Looks good to me!

2022-02-08 22:23 UTC, merged