Package loader and fisher
standardhealth/fhir-matches pull request #4
Opened 2022-03-09 23:40 UTC by julianxcarter

Implements dependency loading and fishing within FM. The fisher works similarly to the `MasterFisher` in SUSHI and GoFSH, but it really only fishes within `FHIRDefinitions` so I thought it wasn't worthy of being a master. 

These changes rely upon the new [FHIR Package Loader](https://github.com/standardhealth/fhir-package-loader) tool. I chose to integrate the new module into this project by running `npm pack` from the base of the `fhir-package-loader` repo, copying the generated `.tgz` file into the FM project, and then running `npm install <generated-tgz-name>.tgz>`

2022-03-29 20:28 UTC, jafeltra reviewed
I just reviewed this, and it looks pretty good! Some of my comments I think we can talk about how FPL should work. There's also a few that are probably more than trivial, so we can talk about how/if we want to address them here.

2022-03-29 20:28 UTC, jafeltra commented on src/utils/Fisher.ts
> +          );
Okay I also just realized this is a major shortcoming of FPL. I _think_ FPL should be able to do this for you, so that here you can just do `this.fhirDefs.fishForFHIR(item, Type.Resource)`, but the `fishForFHIR` in FPL I think is actually implemented wrong. I think it doesn't look through every definition in any package, like you do here with `allResources`. So. Oops. I guess this is another thing we can talk about where to make the change, but I'm thinking FPL. But I guess it also doesn't hurt to keep this implementation here.

2022-03-29 20:28 UTC, jafeltra commented on src/utils/Fisher.ts
> +          );
In the test coverage, it looks like this is the only case that's covered. That's bringing down the totals in the coverage report. I think ideally it would be good to cover all the cases here. However, two things to consider before we do that: 
- Do we want to put that time/effort into this PR now?
- Do we want to do that before we decide about the comment about how FPL's `fishForFHIR` implementation works?

2022-03-29 20:28 UTC, jafeltra commented on test/utils/Dependencies.test.ts
> +});
It might be worthwhile to add a few tests for `determineCorePackageId`. Then again, that function is pretty straightforward, I don't know that the functionality was ever tested in SUSHI explicitly, and again I'm not sure what effort we want to put into this PR right now. But I did notice that the coverage report has it marked as uncovered.

2022-03-29 20:28 UTC, jafeltra commented on test/utils/Fisher.test.ts
> +  describe('fishForFHIR', () => {
As mentioned above, it might be good to (eventually?) add test for the other types besides just `Type.Profile`.

2022-03-29 20:28 UTC, jafeltra commented on test/utils/Fisher.test.ts
> +  describe('fishForFHIR', () => {
It might also be good to add a test to check all types are fished for if no type is specified.

2022-03-30 18:30 UTC, jafeltra commented on src/utils/Fisher.ts
> +          );
Okay I think with the latest version of FPL you should be able to just do `this.fhirDefs.fishForFHIR(item, Type.Resource)` here (and in the other cases as well), and it should work properly now!

2022-03-30 18:31 UTC, jafeltra commented on src/app.ts
> +    }
Alrighty, I updated how FPL works, so you can actually leave the `loadDependency` calls as they are here, and the returned `defs` will be in the correct format. I guess it's still TBD on if you want to rework where these calls get made, but if they are kept as is, `defs` is at least in the correct format now!

2022-03-31 18:25 UTC, julianxcarter commented
Thanks for the review @jafeltra! Commit [`8bc4d72`](https://github.com/standardhealth/fhir-matches/pull/4/commits/8bc4d72ed1f7c6ab2ce32df56c3da737e0447f03) does the following:

- Updates the `Fisher` to use the new fishing functions from FPL
- Updates the core FHIR loading logic in `loadExternalDependencies` and the main `app` function to only occur if the core FHIR version haven't been specified as a dependency
- Fixes the typos since I appear to be incapable of spelling "dependency"
- Fixes the weird console logging in the unit tests
- Adds `TODOs` for unit tests that would be useful in the future

2022-04-01 14:53 UTC, jafeltra commented on src/app.ts
> +      if (!defs.childFHIRDefs.filter(def => def.package === `${fhirPackageId}#${a.fhirVersion}`)) {
Based on the logic here, I think you might want to be using `.find` instead of `.filter`. `filter` will return an empty array if the package isn't found, but `![]` evaluates to false, which is not what we want here.

2022-04-01 15:51 UTC, jafeltra commented on src/app.ts
> +      if (!defs.childFHIRDefs.filter(def => def.package === `${fhirPackageId}#${a.fhirVersion}`)) {
Hello I am back again! I added `allPackages` into FPL, which will do the recursive search and return a flat array of `packageId#version` strings for each package that is loaded into Definitions. So this comment should be set now!

2022-04-01 15:52 UTC, jafeltra commented on src/app.ts
> +      if (!defs.childFHIRDefs.filter(def => def.package === `${fhirPackageId}#${a.fhirVersion}`)) {
Now that `allPackages` is in FPL, you can also update this to use `allPackages()` instead of `childFHIRDefs`!

2022-04-05 13:36 UTC, julianxcarter commented on src/app.ts
> +      if (!defs.childFHIRDefs.filter(def => def.package === `${fhirPackageId}#${a.fhirVersion}`)) {
Commit [`5b24740`](https://github.com/standardhealth/fhir-matches/pull/4/commits/5b24740eec8591254b815d376810344f140b48f9) updates this line (and the one for resource b) to use `allPackages()` from FPL, and to `find()` instead of `filter()`.

2022-04-05 13:40 UTC, jafeltra approved these changes
Looks good @julianxcarter!! Thanks for making all those updates!

2022-04-05 17:04 UTC, mint-thompson requested changes
This looks good! The only things that I would take another look at are some of your TODO comments in your tests, because I think you have completed some of the things that you wrote a TODO for.

2022-04-05 17:04 UTC, mint-thompson commented on test/utils/Dependencies.test.ts
> +  // TODO: Add a describe bloc for determineCorePackageId
It looks like you added this block, so you can remove this comment.

2022-04-05 19:44 UTC, jafeltra commented on test/utils/Dependencies.test.ts
> +  // TODO: Add a describe bloc for determineCorePackageId
Omg did I just completely miss those tests earlier? 🤦‍♀️

2022-04-06 17:26 UTC, jafeltra approved these changes

2022-04-06 19:45 UTC, mint-thompson approved these changes

2022-04-07 12:55 UTC, merged